language: python

python:
  - "3.6"

before_install:
  - export TZ=Europe/Istanbul

install:
  - pip install -r requirements.txt

services:
  - docker

script:
  - make test

after_script:
  - make coverage && codecov